./tests/test_actions_generation/test_actions_generation_pipeline.py: line 1: import: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 2: import: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 4: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 5: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 6: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 7: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 8: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 9: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 10: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 11: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 12: from: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 18: TASKS_CACHE_DIR: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 20: USE_CACHED_TASKS: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 21: NUMBER_OF_TASKS: command not found
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 24: syntax error near unexpected token `('
./tests/test_actions_generation/test_actions_generation_pipeline.py: line 24: `def load_tasks_from_json() -> list[Task] | None:'
